name: Update README
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Commit log change
        run: |
          echo "README update triggered at $(date)" >> log.txt
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update README cache" || true

      - name: Push changes
        env:
          TOKEN: ${{ secrets.PAT }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/onikahmed/onikahmed.git
          git push origin main
