name: Update README
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update README
        run: |
          # No changes needed - just triggers GitHub's cache refresh
          echo "README update triggered at $(date)" >> log.txt
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update README cache" || true
          git push
